### ISSUE TITLE
product version fails on osx 12.5

### ISSUE THREAD

**Issue by davidszotten** [njsmith/posy#5]
on osx 12.5 my version string is reported as 
`[src/platform_tags/macos.rs:94] &product_version_str = "12.5\0"`

making the assertion just below fail
`assert!(pieces.len() == 3);`

**Comment by maccam912** [comment]
Same on 13.1, considering https://github.com/njsmith/posy/blob/1cfd7abb3893478dfa37704b310529c85cadc2b3/src/platform_tags/macos.rs#L102 throws out the last part anyway, it seems like the last piece could just be an optional? This is assuming there are macos versions that DO return 3 pieces.
